### ISSUE TITLE
Merchant List 권한 문제

### ISSUE THREAD

**Issue by grapgrapMMT** [nachwon/Shippa_Order_Project#28]
![image](https://user-images.githubusercontent.com/45350699/73118048-ce2bb480-3f91-11ea-9020-1d53ec29dd47.png)

로그인 하지 않은 상태로 Merchant List를 호출하면 권한 문제로 가져 올수 없습니다.

정책 상 Menu를 로그인 하지 않고 볼 수 있게 해야 하기 때문에, Merchant List 또한 로그인 하지 않은 상태로 볼 수 있어야 합니다.

민감한 정보 때문이라면, 권한에 따라 비로그인 유저는 최소 Merchant Id만 들어있는 List를 받아야 합니다.

@cozaro

**Comment by supercozaro** [comment]
이거 지금 배포 잘못되어있는거 같아요

2020년 1월 25일 (토) 오후 4:45, grapgrap <notifications@github.com>님이 작성:

**Comment by supercozaro** [comment]
.....................................

Dowon 님이 회원님과 연락하고 싶어합니다.

Dowon Koo
MyMusicTaste Back End Developer
대한민국

프로필 보기 https://www.linkedin.com/comm/in/dowon-koo-b244a81a6?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-426-null-null-%7E9e5nog%7Ek8mtpz86%7Ead-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BQgJuGF7hQqCSRRSF5XjjrA%3D%3D

Dowon 님을 아세요? https://www.linkedin.com/comm/start/accept-invitation?sharedKey=HmiDDcIs&invitationId=6652491974660194305&trk=eml-guest-invite-cta&trkEmail=eml-email_m2g_invite_single_01-null-423-null-null-%7E9e5nog%7Ek8mtpz86%7Ead-ssuw-start%7Esignup%7Ewarm&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BQgJuGF7hQqCSRRSF5XjjrA%3D%3D


.....................................

메일 받지 않기: https://www.linkedin.com/e/v2?e=-9e5nog-k8mtpz86-ad&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=434&m=unsub&ts=unsub&loid=AQEBx80NIhQSLQAAAXFJmWqw2Uz6V3HUMPey7aiFjmGrNDI-X3d6nIZqWYWpco4O0HM6xkMo_q0cZlHEI-LtcLpxTlumWxjl87F9BMLG0ZGfXsPsooANP4QTSZPfdD9mZuPoZNqfS_PsO0UdmnZpfvqwQOp7i11Lxw&eid=-9e5nog-k8mtpz86-ad

도움말: https://www.linkedin.com/e/v2?e=-9e5nog-k8mtpz86-ad&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BQgJuGF7hQqCSRRSF5XjjrA%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=433&m=footer&ts=help&articleId=67


현재 1촌 신청 메일을 받고 계십니다. 이메일 주소록을 통해 1촌을 맺을 수 있는 사람을 추천해 드립니다.

reply@reply.github.com 님에게 발송된 메일입니다.

© 2020 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn은 LinkedIn Ireland Unlimited Company의 등록 사업자명입니다. LinkedIn과 LinkedIn 로고는 LinkedIn의 등록 상표입니다.

**Comment by supercozaro** [comment]
님 안녕하세요.

Dowon 님이 LinkedIn 1촌을 신청했습니다. 수락하시겠어요?

수락 https://www.linkedin.com/comm/start/accept-invitation?trk=eml-email_first_guest_reminder_03-hero-21-accept_text&trkEmail=eml-email_first_guest_reminder_03-hero-21-accept_text-null-%7E9e5nog%7Ek8swi1cy%7Ev-ssuw-start%7Esignup%7Ewarm&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3Bq241R26ETgiwBvuXlVHPmQ%3D%3D

Dowon 님의 프로필 보기 https://www.linkedin.com/comm/in/dowon-koo-b244a81a6?trk=eml-email_first_guest_reminder_03-hero-3-prof%7Ename&trkEmail=eml-email_first_guest_reminder_03-hero-3-prof%7Ename-null-%7E9e5nog%7Ek8swi1cy%7Ev-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3Bq241R26ETgiwBvuXlVHPmQ%3D%3D



.....................................

메일 받지 않기: https://www.linkedin.com/e/v2?e=-9e5nog-k8swi1cy-v&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_first_guest_reminder_03&li=18&m=unsub&ts=unsub&loid=AQEPiI9Ur3CR6QAAAXFfgG7sodOXLO86XGspLDsPOr7c941JjsMqYbEvd25BJXPB5vHNEJW4yFOdLe8IggsJpyj81sBJ8hO9Auwr92T85A8978tT7S9MwjtuLV3NMqoHswI625DvH_zdmqVqr6w829KGfJUBBZdKaFGbIw&eid=-9e5nog-k8swi1cy-v

도움말: https://www.linkedin.com/e/v2?e=-9e5nog-k8swi1cy-v&lipi=urn%3Ali%3Apage%3Aemail_email_first_guest_reminder_03%3Bq241R26ETgiwBvuXlVHPmQ%3D%3D&a=customerServiceUrl&ek=email_first_guest_reminder_03&li=17&m=footer&ts=help&articleId=67


 이메일 주소록을 통해 1촌을 맺을 수 있는 사람을 추천해 드립니다.

reply@reply.github.com 님에게 발송된 메일입니다.

© 2020 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn은 LinkedIn Ireland Unlimited Company의 등록 사업자명입니다. LinkedIn과 LinkedIn 로고는 LinkedIn의 등록 상표입니다.

**Comment by supercozaro** [comment]
https://www.linkedin.com/comm/start/accept-invitation?trk=eml-email_second_guest_reminder_03-hero-12-accept_text&trkEmail=eml-email_second_guest_reminder_03-hero-12-accept_text-null-%7E9e5nog%7Ek92x9b8a%7Efs-ssuw-start%7Esignup%7Ewarm&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3B50bq1KWYQW%2Bp6whFxEkCfg%3D%3D

 https://www.linkedin.com/comm/in/dowon-koo-b244a81a6?trk=eml-email_second_guest_reminder_03-hero-3-prof%7Ename&trkEmail=eml-email_second_guest_reminder_03-hero-3-prof%7Ename-null-%7E9e5nog%7Ek92x9b8a%7Efs-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3B50bq1KWYQW%2Bp6whFxEkCfg%3D%3D



.....................................

메일 받지 않기: https://www.linkedin.com/e/v2?e=-9e5nog-k92x9b8a-fs&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_second_guest_reminder_03&li=9&m=unsub&ts=unsub&loid=AQHrdRS2TjHRkQAAAXGDnj9gP4MRepJ8K0F0IQ_Dx9Hwrb3eKz4ylaLeQyOfjCss_AjYW2nfGyIf6WjxFpMDlYriynsdMAhPjJIyG3X6-Wkq5M8sXgQhXM50qaxaFlsLZAN-V32tWQkyjPxSGcS_2bR999Hbzi6hiGdNOw&eid=-9e5nog-k92x9b8a-fs

도움말: https://www.linkedin.com/e/v2?e=-9e5nog-k92x9b8a-fs&lipi=urn%3Ali%3Apage%3Aemail_email_second_guest_reminder_03%3B50bq1KWYQW%2Bp6whFxEkCfg%3D%3D&a=customerServiceUrl&ek=email_second_guest_reminder_03&li=8&m=footer&ts=help&articleId=67


현재 1촌 신청 알림 메일을 받고 계십니다. 이메일 주소록을 통해 1촌을 맺을 수 있는 사람을 추천해 드립니다.

reply@reply.github.com님에게 발송된 메일입니다.

© 2020 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn은 LinkedIn Ireland Unlimited Company의 등록 사업자명입니다. LinkedIn과 LinkedIn 로고는 LinkedIn의 등록 상표입니다.
